# Docker profile - uses emulator
# Spring Cloud GCP configuration
spring.cloud.gcp.pubsub.project-id=${PUBSUB_PROJECT_ID:playground}
spring.cloud.gcp.pubsub.emulator-host=${PUBSUB_EMULATOR_HOST:pubsub-emulator:8085}
spring.cloud.gcp.credentials.enabled=false

